# Generated by Django 3.2.4 on 2021-07-17 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='lon',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='key',
            field=models.UUIDField(default=uuid.UUID('fb8cf6ee-b718-4b2d-acea-8f5b486ea42b'), primary_key=True, serialize=False),
        ),
    ]
